### ISSUE TITLE
todo re: Extensions

### ISSUE THREAD

**Issue by hugoledoux** [tudelft3d/cityjson#36]
- [ ] do we enfore a "namespace" for extra attributes? By have like "+Noise-attribute". This would avoid clashes between diff Extensions, but makes the whole thing more complex. 
- [ ] where are the extensions files? If they are in a subfolder of schemas `/extensions/` then it means that for CityJSON types to be reused one must write have relative path `../cityobjects.json`
- [ ] rename schemas to `cityjson.schema.json`, like glTF does?
